# How often do you want to save output images during training.
image_save_iter: 800
# How often do you want to save trained models.
snapshot_save_iter: 200
snapshot_save_start_iter: 300
# How often do you want to log the training stats.
logging_iter: 100
# Number of training epochs.
max_epoch: 200

# trainer options
trainer:
    type: imaginaire.trainers.pix2pixHD
    amp_config:
        enabled: True
    model_average_config:
        enabled: False
        beta: 0.999
        start_iteration: 500
        num_batch_norm_estimation_iterations: 0

    gan_mode: hinge
    gan_relativistic: False
    perceptual_loss:
        mode: 'vgg19'
        layers: ['relu_1_1', 'relu_2_1', 'relu_3_1', 'relu_4_1', 'relu_5_1']
        weights: [0.03125, 0.0625, 0.125, 0.25, 1.0]
    loss_weight:
        gan: 1.0
        feature_matching: 10.0
        perceptual: 10.0
    init:
        type: xavier
        gain: 0.02

# model options
gen:
    type: imaginaire.generators.pix2pixHD
    global_generator:
        num_filters: 64
        num_downsamples: 3
        num_res_blocks: 9
    local_enhancer:
        num_enhancers: 2
        num_res_blocks: 3
    weight_norm_type: spectral
    activation_norm_type: instance
    padding_mode: reflect

dis:
    type: imaginaire.discriminators.multires_patch
    num_filters: 64
    max_num_filters: 512
    num_discriminators: 2
    num_layers: 3
    weight_norm_type: spectral
    activation_norm_type: instance

# optimization option
gen_opt:
    type: adam
    lr: 0.0002
    adam_beta1: 0.5
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.1
dis_opt:
    type: adam
    lr: 0.0002
    adam_beta1: 0.5
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.1

# Data options.
data:    
    name: 'cityscapes'    
    type: imaginaire.datasets.paired_images    
    num_workers: 4
    input_types:
        - images:
            ext: png
            num_channels: 3
            normalize: True
        - images_rgb:
            ext: png
            num_channels: 3
            normalize: True
        - lidar_seg:
            ext: png
            num_channels: 1
            is_mask: True
            normalize: False



    full_data_ops: imaginaire.model_utils.label::make_one_hot, imaginaire.model_utils.label::concat_labels
    use_dont_care: False
    one_hot_num_classes:
        lidar_seg: 1
    input_labels:
        - lidar_seg
        - images_rgb
    input_image:
         - images
  
    # Train dataset details.
    train:        
        roots:
            - ../../../Datasets/kitti-step/all_train/DurLAR_20210716_S

        batch_size: 8
        augmentations:
            resize_smallest_side: 256
            random_scale_limit: 0.1
            horizontal_flip: False
            random_crop_h_w: 256, 768            

    # Validation dataset details.
    val:        
        roots:
            - ../../../Datasets/kitti-step/all_train/DurLAR_20210716_S
        batch_size: 1        
        augmentations:
            resize_h_w: 256, 768
            horizontal_flip: False

pretrained_weight: 1B3bXpQQzidJW0G3oCjYSWYEn2zd8h9dg
inference_args:
    random_style: False

test_data:    
    name: 'cityscapes'    
    type: imaginaire.datasets.paired_images    
    num_workers: 4
    input_types:
        - images_rgb:
            ext: png
            num_channels: 3
            normalize: True
        - lidar_seg:
            ext: png
            num_channels: 1
            is_mask: True
            normalize: False



    full_data_ops: imaginaire.model_utils.label::make_one_hot, imaginaire.model_utils.label::concat_labels
    use_dont_care: False
    one_hot_num_classes:
        lidar_seg: 1
    input_labels:
        - lidar_seg
        - images_rgb

        
    
    paired: True    
    test:
        is_lmdb: False
        roots:


     
        batch_size: 1        
        augmentations:
            #resize_h_w: 512, 1024
            resize_h_w: 256, 768
            horizontal_flip: False