# How often do you want to save output images during training.
image_save_iter: 8000
# How often do you want to save trained models.
snapshot_save_iter: 2000
snapshot_save_start_iter: 3000
# How often do you want to log the training stats.
logging_iter: 1000
# Number of training epochs.
max_epoch: 20

# trainer options
trainer:
    type: imaginaire.trainers.pix2pixHD
    amp_config:
        enabled: True
    model_average_config:
        enabled: False
        beta: 0.999
        start_iteration: 500
        num_batch_norm_estimation_iterations: 0

    gan_mode: hinge
    gan_relativistic: False
    perceptual_loss:
        mode: 'vgg19'
        layers: ['relu_1_1', 'relu_2_1', 'relu_3_1', 'relu_4_1', 'relu_5_1']
        weights: [0.03125, 0.0625, 0.125, 0.25, 1.0]
    loss_weight:
        gan: 1.0
        feature_matching: 10.0
        perceptual: 10.0
    init:
        type: xavier
        gain: 0.02

# model options
gen:
    type: imaginaire.generators.pix2pixHD
    global_generator:
        num_filters: 64
        num_downsamples: 3
        num_res_blocks: 9
    local_enhancer:
        num_enhancers: 2
        num_res_blocks: 3
    weight_norm_type: spectral
    activation_norm_type: instance
    padding_mode: reflect

dis:
    type: imaginaire.discriminators.multires_patch
    num_filters: 64
    max_num_filters: 512
    num_discriminators: 2
    num_layers: 3
    weight_norm_type: spectral
    activation_norm_type: instance

# optimization option
gen_opt:
    type: adam
    lr: 0.0002
    adam_beta1: 0.5
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.1
dis_opt:
    type: adam
    lr: 0.0002
    adam_beta1: 0.5
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: False
        type: step
        step_size: 100
        gamma: 0.1

# Data options.
data:    
    name: 'cityscapes'    
    type: imaginaire.datasets.paired_images    
    num_workers: 4
    input_types:
        - images:
            ext: png
            num_channels: 1
            normalize: True
        - color_big:
            ext: png
            num_channels: 3
            normalize: True
        - lidar_depth8:
            ext: png
            num_channels: 1
            normalize: True
        - lidar_seg:
            ext: png
            num_channels: 1
            is_mask: True
            normalize: False
        - lidar_inst:
            ext: png
            num_channels: 1
            is_mask: True
            normalize: False


    full_data_ops: imaginaire.model_utils.label::make_one_hot, imaginaire.model_utils.label::concat_labels
    use_dont_care: False
    one_hot_num_classes:
        lidar_seg: 20
    input_labels:
        - lidar_seg
 #       - lidar_depth8
 #       - color_big
 #       - lidar_inst
    input_image:
         - images
  
    # Train dataset details.
    train:        
        roots:
            - ../../../Datasets/kitti-step/all_train/0000
            - ../../../Datasets/kitti-step/all_train/0003
            - ../../../Datasets/kitti-step/all_train/0004
            - ../../../Datasets/kitti-step/all_train/0005
            - ../../../Datasets/kitti-step/all_train/0007
            - ../../../Datasets/kitti-step/all_train/0008
            - ../../../Datasets/kitti-step/all_train/0009
            - ../../../Datasets/kitti-step/all_train/0010
            - ../../../Datasets/kitti-step/all_train/0011
            - ../../../Datasets/kitti-step/all_train/0012
            - ../../../Datasets/kitti-step/all_train/0013
            - ../../../Datasets/kitti-step/all_train/0014
            - ../../../Datasets/kitti-step/all_train/0015
            - ../../../Datasets/kitti-step/all_train/0016
            - ../../../Datasets/kitti-step/all_train/0017
            - ../../../Datasets/kitti-step/all_train/0019

        batch_size: 8
        augmentations:
            resize_smallest_side: 64
            random_scale_limit: 0.1
            horizontal_flip: False
            random_crop_h_w: 64, 512            

    # Validation dataset details.
    val:        
        roots:
            - ../../../Datasets/kitti-step/all_val/0002 
            - ../../../Datasets/kitti-step/all_val/0006
            - ../../../Datasets/kitti-step/all_val/0018
            - ../../../Datasets/kitti-step/all_val/0001  
            - ../../../Datasets/kitti-step/all_val/0020  
        batch_size: 1        
        augmentations:
            resize_h_w: 64, 512
            horizontal_flip: False

pretrained_weight: 1B3bXpQQzidJW0G3oCjYSWYEn2zd8h9dg
inference_args:
    random_style: False

test_data:    
    name: 'cityscapes'    
    type: imaginaire.datasets.paired_images    
    num_workers: 4
    input_types:
        - color_big:
            ext: png
            num_channels: 3
            normalize: True
        - lidar_depth8:
            ext: png
            num_channels: 1
            normalize: True
        - lidar_seg:
            ext: png
            num_channels: 1
            is_mask: True
            normalize: False
        - lidar_inst:
            ext: png
            num_channels: 1
            is_mask: True
            normalize: False



    full_data_ops: imaginaire.model_utils.label::make_one_hot, imaginaire.model_utils.label::concat_labels
    use_dont_care: False
    one_hot_num_classes:
        lidar_seg: 20
    input_labels:
        - lidar_seg
#        - lidar_depth8
#        - color_big
#        - lidar_inst
        
    
    paired: True    
    test:
        is_lmdb: False
        roots:
            - ../../../Datasets/kitti-step/all_val/0001
            - ../../../Datasets/kitti-step/VKITTI/0001

     
        batch_size: 1        
        augmentations:
            #resize_h_w: 512, 1024
            resize_h_w: 64, 512
            horizontal_flip: False